notifications:
    commits:      events@mxnet.apache.org
    issues:       events@mxnet.apache.org
    pullrequests: events@mxnet.apache.org

github:
  features:
    wiki: true
    issues: true
    projects: true

  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  true
